# Generated by Django 5.2.14 on 2026-05-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConjunctionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norad_primary', models.CharField(help_text='NORAD ID of the primary (larger) object', max_length=10)),
                ('name_primary', models.CharField(blank=True, max_length=100)),
                ('norad_secondary', models.CharField(help_text='NORAD ID of the secondary (debris/payload)', max_length=10)),
                ('name_secondary', models.CharField(blank=True, max_length=100)),
                ('poc_score', models.FloatField(help_text='ML-inferred Probability of Collision')),
                ('miss_distance', models.FloatField(help_text='Miss distance in km at TCA')),
                ('rel_velocity', models.FloatField(default=0.0, help_text='Relative velocity in km/s at TCA')),
                ('tca', models.DateTimeField(help_text='Time of Closest Approach (UTC)')),
                ('severity', models.CharField(choices=[('low', 'Low (PoC < 1e-4)'), ('medium', 'Medium (1e-4 ≤ PoC < 1e-3)'), ('high', 'High (PoC ≥ 1e-3)'), ('critical', 'Critical (PoC ≥ 1e-2)')], default='low', max_length=10)),
                ('is_debris', models.BooleanField(default=False)),
                ('cdm_id', models.CharField(blank=True, help_text='Space-Track CDM_ID if available', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Conjunction Alert',
                'verbose_name_plural': 'Conjunction Alerts',
                'ordering': ['-poc_score'],
            },
        ),
        migrations.CreateModel(
            name='RejectedTLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norad_id', models.CharField(db_index=True, help_text='NORAD catalogue number of the rejected object', max_length=10)),
                ('object_name', models.CharField(blank=True, help_text='Common name as supplied in the TLE header line', max_length=100)),
                ('reason', models.CharField(help_text='Human-readable rejection reason from the validator', max_length=200)),
                ('raw_line1', models.TextField(blank=True, help_text='Raw TLE line 1 (69 chars)')),
                ('raw_line2', models.TextField(blank=True, help_text='Raw TLE line 2 (69 chars)')),
                ('rejected_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp of rejection')),
            ],
            options={
                'verbose_name': 'Rejected TLE',
                'verbose_name_plural': 'Rejected TLEs',
                'ordering': ['-rejected_at'],
            },
        ),
    ]
